name: New Version

on:
  push:
    branches: [temp]

jobs:
  instance_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: AWS Configure
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Get Latest AMI ID
        id: get-ami
        run: |
          latest_ami_id=$(aws ec2 describe-images --query 'Images[?Name==`csye6225*`].ImageId' --output text)
          echo "::set-output name=ami_id::$latest_ami_id"
      
      - name: Print Latest AMI ID
        run: |
          echo "Latest AMI ID: ${{ steps.get-ami.outputs.ami_id }}"